def is_discharging() -> bool: ...
def is_charging() -> bool: ...
def percent() -> int: ...
def minutes_remaining() -> int | None: ...
def minutes_until_charged() -> int | None: ...
def capacity() -> int: ...
def design_capacity() -> int: ...
